### ISSUE TITLE
Resolve how to connect wii to our new TV

### ISSUE THREAD

**Issue by jobow1** [WinsorCottageBow/WinsorCottage#70]

**Comment by rogers492** [comment]
Here's how: https://itstillworks.com/12267243/how-to-connect-a-wii-to-hdmi

**Comment by rogers492** [comment]
Wiil give this a go: https://www.amazon.co.uk/Adapter-GANA-Converter-Connector-Output/dp/B078Y58RN9/ref=sr_1_1?s=diy&ie=UTF8&qid=1532503423&sr=8-1&keywords=wii+to+hdmi

**Comment by rogers492** [comment]
Connector on order from Amazon.

**Comment by rogers492** [comment]
That works. Just waiting for delivery of new sensor strip.
